### ISSUE TITLE
Update fileLoader to read bin/texture files from remote URL

### ISSUE THREAD

**Issue by silvainSayduck** [TimvanScherpenzeel/gltf-to-usdz#8]
Hi,

I saw that you have already abstracted a `fileLoader` (which currently is just a `fs` wrapper): could that mean that you are planning to add support for automatic remote file download in this project? This would make this converter extremely flexible, and directly usable for our needs, since we are internally using `glTF`s with remote assets stored on Amazon S3.

I am aware the `http[s]://` URIs are in fact not clearly part of the glTF 2.0 standard, but we decided that for web purposes it made a lot more sense to keep assets separate, especially because we have a lot of cases where many assets are shared between different models.

Thanks for the awesome work in any case!

**Comment by TimvanScherpenzeel** [comment]
Hi @silvainSayduck,

I've separated out the `fileLoader` because I like to have a similar file structure across multiple projects. I am not planning to add such functionality as this is merely a proof of concept, not meant to be integrated into a production pipeline. I would highly recommend https://github.com/kcoley/gltf2usd that is in active development and should offer the functionality you are looking for.

**Comment by silvainSayduck** [comment]
Alright, thanks a lot for the pointer!
